# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506cd2d43c01085e4ae9b10477d1d4a0acce0745e94d6491d6f856a5574912f88f9f040d3138047c9220686eeb59d492a1f90125e6e8713849a536ea77b14f78
  facebook_app_id: <%= ENV["YELP_CLONE_FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["YELP_CLONE_FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: d62e1709e008740e3e00d1966dfcbebcc250e4b9018b6f3705a5b434d897746d83a3a86f835835c7833bd42fd91b15f9ff3e5724268aa76d6c438ba30ef6cbcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["YELP_CLONE_FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["YELP_CLONE_FACEBOOK_APP_SECRET"] %>
